const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

/**
 * Everything Hermes Code - Hook System
 * 
 * Manages pre-commit, post-commit, and pre-push hooks
 * for automated code quality checks.
 */

const hooks = [
  {
    name: 'pre-commit',
    type: 'pre',
    tool: 'bash',
    description: 'Run markdown linting before commit',
    script: 'pre-commit.sh'
  },
  {
    name: 'post-commit',
    type: 'post',
    tool: 'bash',
    description: 'Log commit information',
    script: 'post-commit.sh'
  },
  {
    name: 'pre-push',
    type: 'pre',
    tool: 'bash',
    description: 'Run final checks before push',
    script: 'pre-push.sh'
  }
];

/**
 * Execute a hook script
 */
function executeHook(hook) {
  const scriptPath = path.join(__dirname, 'scripts', hook.script);
  
  if (!fs.existsSync(scriptPath)) {
    console.error(`❌ Hook script not found: ${scriptPath}`);
    return false;
  }

  try {
    console.log(`🔍 Running ${hook.name} hook...`);
    execSync(`bash "${scriptPath}"`, { 
      stdio: 'inherit',
      cwd: process.cwd()
    });
    console.log(`✅ ${hook.name} hook completed`);
    return true;
  } catch (error) {
    console.error(`❌ ${hook.name} hook failed:`, error.message);
    return false;
  }
}

/**
 * Install hooks into .git/hooks
 */
function installHooks() {
  const gitHooksDir = path.join(process.cwd(), '.git', 'hooks');
  
  if (!fs.existsSync(gitHooksDir)) {
    console.error('❌ .git/hooks directory not found');
    return false;
  }

  hooks.forEach(hook => {
    const hookPath = path.join(gitHooksDir, hook.name);
    const scriptPath = path.join(__dirname, 'scripts', hook.script);
    
    const hookContent = `#!/bin/bash
# Auto-generated by everything-hermes-code
exec bash "${scriptPath}" "$@"
`;
    
    fs.writeFileSync(hookPath, hookContent, { mode: 0o755 });
    console.log(`✅ Installed ${hook.name} hook`);
  });

  return true;
}

/**
 * List available hooks
 */
function listHooks() {
  console.log('Available hooks:');
  console.log('================');
  
  hooks.forEach(hook => {
    console.log(`  ${hook.name} (${hook.type}) - ${hook.description}`);
  });
}

// Export for use in other scripts
module.exports = {
  hooks,
  executeHook,
  installHooks,
  listHooks
};

// CLI interface
if (require.main === module) {
  const command = process.argv[2];
  
  switch (command) {
    case 'install':
      installHooks();
      break;
    case 'list':
      listHooks();
      break;
    case 'run':
      const hookName = process.argv[3];
      const hook = hooks.find(h => h.name === hookName);
      if (hook) {
        executeHook(hook);
      } else {
        console.error(`❌ Hook not found: ${hookName}`);
      }
      break;
    default:
      console.log('Usage: node index.js [install|list|run <hook-name>]');
  }
}
